const FIVE_MINUTES_IN_SECONDS = 300
const SIXTY_MINUTES_IN_SECONDS = 3600
const THIRTY_DAYS_IN_SEC = 2592000;
const TWO_HOURS_IN_SEC = 7200;

module.exports = {
    FIVE_MINUTES_IN_SECONDS,
    SIXTY_MINUTES_IN_SECONDS,
    THIRTY_DAYS_IN_SEC,
    TWO_HOURS_IN_SEC
}
